Remove empty diff requirements
rhysr/releases pull request #11
Opened 2017-03-02 20:26 UTC by tkjn

If a diff requirement is edited in the Add Diff form and reverted before submission, it would still be present to in the requirements object.
This could cause the "Requirements" button to appear when viewing a diff with no requirements.
Unchecked or empty requirements will now be removed before saving to the firebase.

Also fixes:
 - Mispelt key in diff initialisation
 - Incorrect submit button text on Add Diff form

2017-03-02 22:43 UTC, rhysr requested changes

2017-03-02 22:43 UTC, rhysr commented on public/javascripts/releases-controllers.js
> +                if (!$scope.newDiff.requirements[key]) {
When iterating over a hash, you should use the hasOwnProperty method to ensure that the key is not an inherited property.
Run jshint on this if in doubt

2017-03-03 18:13 UTC, tkjn commented on public/javascripts/releases-controllers.js
> +                if (!$scope.newDiff.requirements[key]) {
I couldn't find any issues with this file with jshint. Maybe I did it wrong...
Changed it any way.

2017-03-08 08:25 UTC, rhysr approved these changes

2017-03-08 08:26 UTC, merged